reprint: Reprint please specify
curr: Current
prev: Previous
next: Next
search: Search
searchTip: Please enter a search keyword
postTagTitle: Post Tags
postCategoryTitle: Post Categories
categoryEmptyTip: Your posts has no categories information yet.